title: Hennesy Strategy
description: "Website description here"
baseurl: ""
url: ""
theme: jekyll-cayman
nav:
  - Home: index.md
  - About: about.md
  - Services: services.md
  - Speaking & Media: speaking-media.md
  - Research: research.md
  - Contact: contact.md
